Downloading the dataset:

In [ ]:
!pip install datasets

Collecting datasets
  Downloading datasets-3.3.2-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from datasets) (3.17.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.11/dist-packages (from datasets) (1.26.4)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.11/dist-packages (from datasets) (18.1.0)
Collecting dill<0.3.9,>=0.3.0 (from datasets)
  Downloading dill-0.3.8-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (from datasets) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.11/dist-packages (from datasets) (2.32.3)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.11/dist-packages (from datasets) (4.67.1)
Collecting xxhash (from datasets)
  Downloading xxhash-3.5.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (12 kB)
Collecting multiprocess<0.70.17 (from datasets)
  Downloading multiprocess-0.70.16-py311-none-any.whl.metadata (7.2 kB)
Requirement already satisfied: fsspec<=2024.12.0,>=2023.1.0 in /usr/local/lib/python3.11/dist-packages (from fsspec[http]<=2024.12.0,>=2023.1.0->datasets) (2024.10.0)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.11/dist-packages (from datasets) (3.11.13)
Requirement already satisfied: huggingface-hub>=0.24.0 in /usr/local/lib/python3.11/dist-packages (from datasets) (0.28.1)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from datasets) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from datasets) (6.0.2)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (2.4.6)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (1.3.2)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (25.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (1.5.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (6.1.0)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (0.3.0)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (1.18.3)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.24.0->datasets) (4.12.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets) (2025.1.31)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets) (2025.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Downloading datasets-3.3.2-py3-none-any.whl (485 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 485.4/485.4 kB 3.9 MB/s eta 0:00:00
Downloading dill-0.3.8-py3-none-any.whl (116 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.3/116.3 kB 9.0 MB/s eta 0:00:00
Downloading multiprocess-0.70.16-py311-none-any.whl (143 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 143.5/143.5 kB 11.9 MB/s eta 0:00:00
Downloading xxhash-3.5.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (194 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 194.8/194.8 kB 9.1 MB/s eta 0:00:00
Installing collected packages: xxhash, dill, multiprocess, datasets
Successfully installed datasets-3.3.2 dill-0.3.8 multiprocess-0.70.16 xxhash-3.5.0

In [ ]:
from datasets import load_dataset
dataset = load_dataset("stanfordnlp/sst")

/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

README.md:   0%|          | 0.00/6.68k [00:00<?, ?B/s]

sst.py:   0%|          | 0.00/9.13k [00:00<?, ?B/s]

The repository for stanfordnlp/sst contains custom code which must be executed to correctly load the dataset. You can inspect the repository content at https://hf.co/datasets/stanfordnlp/sst.
You can avoid this prompt in future by passing the argument `trust_remote_code=True`.

Do you wish to run the custom code? [y/N] y

Downloading data:   0%|          | 0.00/6.37M [00:00<?, ?B/s]

Downloading data:   0%|          | 0.00/790k [00:00<?, ?B/s]

Generating train split:   0%|          | 0/8544 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/1101 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/2210 [00:00<?, ? examples/s]

In [ ]:
dataset

DatasetDict({
    train: Dataset({
        features: ['sentence', 'label', 'tokens', 'tree'],
        num_rows: 8544
    })
    validation: Dataset({
        features: ['sentence', 'label', 'tokens', 'tree'],
        num_rows: 1101
    })
    test: Dataset({
        features: ['sentence', 'label', 'tokens', 'tree'],
        num_rows: 2210
    })
})

In [ ]:
train_data = dataset["train"]
test_data = dataset["test"]
validation_data = dataset["validation"]

In [ ]:
train_data[0]

{'sentence': "The Rock is destined to be the 21st Century 's new `` Conan '' and that he 's going to make a splash even greater than Arnold Schwarzenegger , Jean-Claud Van Damme or Steven Segal .",
 'label': 0.6944400072097778,
 'tokens': "The|Rock|is|destined|to|be|the|21st|Century|'s|new|``|Conan|''|and|that|he|'s|going|to|make|a|splash|even|greater|than|Arnold|Schwarzenegger|,|Jean-Claud|Van|Damme|or|Steven|Segal|.",
 'tree': '70|70|68|67|63|62|61|60|58|58|57|56|56|64|65|55|54|53|52|51|49|47|47|46|46|45|40|40|41|39|38|38|43|37|37|69|44|39|42|41|42|43|44|45|50|48|48|49|50|51|52|53|54|55|66|57|59|59|60|61|62|63|64|65|66|67|68|69|71|71|0'}

converting the dataset to a pandas dataframe:

In [ ]:
import pandas as pd
df_train = pd.DataFrame(dataset["train"])
df_train

,sentence,label,tokens,tree
0,The Rock is destined to be the 21st Century 's...,0.69444,The|Rock|is|destined|to|be|the|21st|Century|'s...,70|70|68|67|63|62|61|60|58|58|57|56|56|64|65|5...
1,The gorgeously elaborate continuation of `` Th...,0.83333,The|gorgeously|elaborate|continuation|of|``|Th...,71|70|69|69|67|67|66|64|63|62|62|61|61|58|57|5...
2,Singer\/composer Bryan Adams contributes a sle...,0.62500,Singer\/composer|Bryan|Adams|contributes|a|sle...,72|71|71|70|68|68|67|67|66|63|62|62|60|60|58|5...
3,You 'd think by now America would have had eno...,0.50000,You|'d|think|by|now|America|would|have|had|eno...,36|35|34|33|33|32|30|29|27|26|25|24|23|23|22|2...
4,Yet the act is still charming here .,0.72222,Yet|the|act|is|still|charming|here|.,15|13|13|10|9|9|11|12|10|11|12|14|14|15|0
...,...,...,...,...
8539,A real snooze .,0.11111,A|real|snooze|.,7|6|5|5|6|7|0
8540,No surprises .,0.22222,No|surprises|.,5|4|4|5|0
8541,We 've seen the hippie-turned-yuppie plot befo...,0.75000,We|'ve|seen|the|hippie-turned-yuppie|plot|befo...,41|40|38|37|36|36|39|42|43|35|34|31|30|30|29|2...
8542,Her fans walked out muttering words like `` ho...,0.13889,Her|fans|walked|out|muttering|words|like|``|ho...,62|62|55|55|53|53|52|51|50|49|48|47|47|57|58|5...
8543,In this case zero .,0.34722,In|this|case|zero|.,8|8|7|6|6|7|9|9|0

In [ ]:
df_test = pd.DataFrame(dataset["test"])
df_validation = pd.DataFrame(dataset["validation"])

Prepocessing for classification:

In [ ]:
bins = [0, 0.2, 0.4, 0.6, 0.8, 1.0]
labels = [0, 1, 2, 3, 4]
def convert_scores_to_classes(scores):
    return pd.cut(scores, bins=bins, labels=labels, include_lowest=True)

df_train["class"] = convert_scores_to_classes(df_train["label"])
df_train["class"] = df_train["class"].astype(int)

df_test["class"] = convert_scores_to_classes(df_test["label"])
df_test["class"] = df_test["class"].astype(int)

df_validation["class"] = convert_scores_to_classes(df_validation["label"])
df_validation["class"] = df_validation["class"].astype(int)

In [ ]:
df_train

,sentence,label,tokens,tree,class
0,The Rock is destined to be the 21st Century 's...,0.69444,The|Rock|is|destined|to|be|the|21st|Century|'s...,70|70|68|67|63|62|61|60|58|58|57|56|56|64|65|5...,3
1,The gorgeously elaborate continuation of `` Th...,0.83333,The|gorgeously|elaborate|continuation|of|``|Th...,71|70|69|69|67|67|66|64|63|62|62|61|61|58|57|5...,4
2,Singer\/composer Bryan Adams contributes a sle...,0.62500,Singer\/composer|Bryan|Adams|contributes|a|sle...,72|71|71|70|68|68|67|67|66|63|62|62|60|60|58|5...,3
3,You 'd think by now America would have had eno...,0.50000,You|'d|think|by|now|America|would|have|had|eno...,36|35|34|33|33|32|30|29|27|26|25|24|23|23|22|2...,2
4,Yet the act is still charming here .,0.72222,Yet|the|act|is|still|charming|here|.,15|13|13|10|9|9|11|12|10|11|12|14|14|15|0,3
...,...,...,...,...,...
8539,A real snooze .,0.11111,A|real|snooze|.,7|6|5|5|6|7|0,0
8540,No surprises .,0.22222,No|surprises|.,5|4|4|5|0,1
8541,We 've seen the hippie-turned-yuppie plot befo...,0.75000,We|'ve|seen|the|hippie-turned-yuppie|plot|befo...,41|40|38|37|36|36|39|42|43|35|34|31|30|30|29|2...,3
8542,Her fans walked out muttering words like `` ho...,0.13889,Her|fans|walked|out|muttering|words|like|``|ho...,62|62|55|55|53|53|52|51|50|49|48|47|47|57|58|5...,0
8543,In this case zero .,0.34722,In|this|case|zero|.,8|8|7|6|6|7|9|9|0,1

In [ ]:
df_train.describe()

             label        class
count  8544.000000  8544.000000
mean      0.510133     2.058052
std       0.251433     1.281570
min       0.000000     0.000000
25%       0.277780     1.000000
50%       0.513890     2.000000
75%       0.736110     3.000000
max       1.000000     4.000000

**Confusion Matrix:**

In [ ]:
import numpy as np

def confusion_matrix(y_true, y_pred, num_classes=5): #initialzing an empty matrix

    matrix = np.zeros((num_classes, num_classes), dtype=int)

    for true, pred in zip(y_true, y_pred):
        matrix[true][pred] += 1

    return matrix

In [ ]:
def precision(matrix,num_classes=5):
    precision = np.zeros(num_classes)

    for i in range(num_classes):
        tp = matrix[i, i]
        fp = np.sum(matrix[:, i]) - tp
        precision[i] = tp / (tp + fp) if (tp + fp) > 0 else 0

    macro_precision = np.mean(precision)
    return precision, macro_precision

In [ ]:
def recall(matrix,num_classes=5):
    recall = np.zeros(num_classes)

    for i in range(num_classes):
        tp = matrix[i, i]
        fn = np.sum(matrix[i, :]) - tp
        recall[i] = tp / (tp + fn) if (tp + fn) > 0 else 0

    macro_recall = np.mean(recall)
    return recall, macro_recall

In [ ]:
def f1_score(matrix,num_classes=5):
    precision_per_class, _ = precision(matrix,num_classes)
    recall_per_class, _ = recall(matrix,num_classes)

    f1 = np.zeros(len(precision_per_class))

    for i in range(len(precision_per_class)):
        p, r = precision_per_class[i], recall_per_class[i]
        f1[i] = (2 * p * r) / (p + r) if (p + r) > 0 else 0

    macro_f1 = np.mean(f1)
    return f1, macro_f1

**Naive Bayes:**

In [ ]:
import numpy as np
from collections import defaultdict

class NaiveBayesClassifier:
    def __init__(self):
        self.logprior = {}
        self.loglikelihood = defaultdict(lambda: defaultdict(float))
        self.vocab = set()
        self.classes = [0, 1, 2, 3, 4]

    def train(self, documents, labels):
        N_doc = len(documents) #total no of documents in the dataset
        class_docs = {c: [] for c in self.classes}      #doc of each class
        word_counts = {c: defaultdict(int) for c in self.classes}      #words of each class
        class_counts = defaultdict(int)     #no of documents in a class

        #combining all documents to make one big document
        for doc, label in zip(documents, labels):
            class_docs[label].append(doc)
            class_counts[label] += 1
            for word in doc.split():
                word_counts[label][word] += 1
                self.vocab.add(word)

        #loop over all classes -> 0 , 1 , 2 , 3 , 4
        for c in self.classes:
            self.logprior[c] = np.log(class_counts[c] / N_doc) #calculating priors
            total_words_in_class = sum(word_counts[c].values())   #number of words in this class
            #calculating the likelihoods
            for word in self.vocab:
                count_wc = word_counts[c][word] + 1  #smoothing -> used the m-estimator with m=1
                denominator = total_words_in_class + len(self.vocab)
                self.loglikelihood[word][c] = np.log(count_wc / denominator)

    def test(self, document):
        sum_log_probs = {c: self.logprior[c] for c in self.classes}
        for word in document.split():
            if word in self.vocab:
                for c in self.classes:
                    sum_log_probs[c] += self.loglikelihood[word][c]
        return max(sum_log_probs, key=sum_log_probs.get)  #we return the class with maximum probbailty

In [ ]:
nb = NaiveBayesClassifier()
x_train = df_train["sentence"].values
y_train = df_train["class"].values
x_test = df_test["sentence"].values
y_test = df_test["class"].values

documents = [str(doc) for doc in x_train]
nb.train(documents, y_train)

y_pred = [nb.test(doc) for doc in x_test]

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB

#numpy arrays -> lists
x_train = x_train.astype(str).tolist()
x_test = x_test.astype(str).tolist()

#bag of words conversion
vectorizer = CountVectorizer()
x_train_bow = vectorizer.fit_transform(x_train)  # Fit and transform training data
x_test_bow = vectorizer.transform(x_test)  # Transform test data (no fit)

#trainig
nb_model = MultinomialNB()
nb_model.fit(x_train_bow, y_train)

#testing
y_pred_sklearn = nb_model.predict(x_test_bow)

**Confusion Matrix:**

In [ ]:
cm_handmade = confusion_matrix(y_test, y_pred)
cm_sklearn = confusion_matrix(y_test, y_pred_sklearn)
precision_handmade, macro_precision_handmade = precision(cm_handmade)
recall_handmade, macro_recall_handmade = recall(cm_handmade)
f1_handmade, macro_f1_handmade = f1_score(cm_handmade)
precision_sklearn, macro_precision_sklearn = precision(cm_sklearn)
recall_sklearn, macro_recall_sklearn = recall(cm_sklearn)
f1_sklearn, macro_f1_sklearn = f1_score(cm_sklearn)
print("Confusion Matrix (Handmade):")
print(cm_handmade)
print("\nConfusion Matrix (Scikit-learn):")
print(cm_sklearn)

Confusion Matrix (Handmade):
[[ 16 201   7  55   0]
 [ 20 409  50 147   7]
 [  8 167  32 176   6]
 [  1  96  24 356  33]
 [  2  38  14 281  64]]

Confusion Matrix (Scikit-learn):
[[ 28 200  10  41   0]
 [ 22 415  57 127  12]
 [  8 154  34 181  12]
 [  2  88  39 340  41]
 [  2  39  12 259  87]]

In [ ]:
print("\nPrecision (Handmade):")
print([f"{p:.4f}" for p in precision_handmade])
print("\nPrecision (Scikit-learn):")
print([f"{p:.4f}" for p in precision_sklearn])

print("\nRecall (Handmade):")
print([f"{r:.4f}" for r in recall_handmade])
print("\nRecall (Scikit-learn):")
print([f"{r:.4f}" for r in recall_sklearn])

print("\nF1 Score (Handmade):")
print([f"{f:.4f}" for f in f1_handmade])
print("\nF1 Score (Scikit-learn):")
print([f"{f:.4f}" for f in f1_sklearn])

Precision (Handmade):
['0.3404', '0.4490', '0.2520', '0.3507', '0.5818']

Precision (Scikit-learn):
['0.4516', '0.4632', '0.2237', '0.3586', '0.5724']

Recall (Handmade):
['0.0573', '0.6461', '0.0823', '0.6980', '0.1604']

Recall (Scikit-learn):
['0.1004', '0.6556', '0.0874', '0.6667', '0.2180']

F1 Score (Handmade):
['0.0982', '0.5298', '0.1240', '0.4669', '0.2515']

F1 Score (Scikit-learn):
['0.1642', '0.5428', '0.1257', '0.4664', '0.3158']

In [ ]:
accuracy_handmade = np.mean(y_test == y_pred)
accuracy_sklearn = nb_model.score(x_test_bow, y_test)
print("Accuracy (Handmade):", f"{accuracy_handmade:.4f}")
print("Accuracy (Scikit-learn):", f"{accuracy_sklearn:.4f}")

Accuracy (Handmade): 0.3968
Accuracy (Scikit-learn): 0.4090

Our models impleneted values are nearly the same as the scikit-learn's built in model.

**Logistic Regression**

In [ ]:
import numpy as np
import pandas as pd
from datasets import load_dataset
from collections import Counter
from sklearn.preprocessing import OneHotEncoder
from scipy.sparse import csr_matrix, hstack, vstack
from sklearn.linear_model import LogisticRegression, SGDClassifier
from sklearn.metrics import accuracy_score, classification_report

In [ ]:
def generate_bigrams(tokens):
    words = tokens.split("|")
    return list(zip(words, words[1:]))

In [ ]:
def build_bigram_vocabulary(df):
    all_bigrams = []
    for tokenized_sentence in df["tokens"]:
        all_bigrams.extend(generate_bigrams(tokenized_sentence))

    # Count bigram frequencies
    bigram_counts = Counter(all_bigrams)

    # Create vocabulary mapping each bigram to an index
    bigram_vocab = {bigram: idx for idx, bigram in enumerate(bigram_counts.keys())}

    print(f"Total unique bigrams: {len(bigram_vocab)}")
    return bigram_vocab

print("\nBuilding bigram vocabulary from training data")
bigram_vocab = build_bigram_vocabulary(df_train)

Building bigram vocabulary from training data
Total unique bigrams: 87247

In [ ]:
def create_sparse_feature_matrix(df, bigram_vocab):
    rows = []
    cols = []
    data = []

    for row_idx, tokenized_sentence in enumerate(df["tokens"]):
        bigrams = generate_bigrams(tokenized_sentence)
        for bigram in bigrams:
            if bigram in bigram_vocab:
                rows.append(row_idx)
                cols.append(bigram_vocab[bigram])
                # 1 if bigram exists
                data.append(1)

    # Create sparse matrix in compressed format to save memory
    X_sparse = csr_matrix((data, (rows, cols)), shape=(len(df), len(bigram_vocab)))
    return X_sparse

In [ ]:
X_train_sparse = create_sparse_feature_matrix(df_train, bigram_vocab)
X_test_sparse = create_sparse_feature_matrix(df_test, bigram_vocab)
X_val_sparse = create_sparse_feature_matrix(df_validation, bigram_vocab)

print(f"Training feature matrix shape: {X_train_sparse.shape}")
print(f"Test feature matrix shape: {X_test_sparse.shape}")
print(f"Validation feature matrix shape: {X_val_sparse.shape}")

Training feature matrix shape: (8544, 87247)
Test feature matrix shape: (2210, 87247)
Validation feature matrix shape: (1101, 87247)

In [ ]:
encoder = OneHotEncoder(sparse_output=True)
y_train_sparse = encoder.fit_transform(df_train["class"].values.reshape(-1, 1))
y_test_sparse = encoder.transform(df_test["class"].values.reshape(-1, 1))
y_val_sparse = encoder.transform(df_validation["class"].values.reshape(-1, 1))

In [ ]:
def initialize_weights(n_features, n_classes):
    # Initialize with small random values
    W = np.random.randn(n_features, n_classes) * 0.01
    b = np.zeros(n_classes)
    return W, b

In [ ]:
def softmax(z):
    # Use the max trick for numerical stability
    exp_z = np.exp(z - np.max(z, axis=1, keepdims=True))
    return exp_z / np.sum(exp_z, axis=1, keepdims=True)

In [ ]:
def compute_loss(y_true, y_pred, W, lambda_reg):
    m = y_true.shape[0]
    # Prevent log(0)
    epsilon = 1e-15

    # cross-entropy
    data_loss = -np.mean(np.sum(y_true * np.log(y_pred + epsilon), axis=1))

    # Regularization loss
    reg_loss = (lambda_reg / (2 * m)) * np.sum(W * W)

    return data_loss + reg_loss

In [ ]:
def compute_gradients(X, y_true, y_pred, W, lambda_reg):
    m = y_true.shape[0]

    # Gradient of weights
    dW = (X.T.dot(y_pred - y_true) / m) + (lambda_reg * W / m)

    # Gradient of bias
    db = np.sum(y_pred - y_true, axis=0) / m

    return dW, db

In [ ]:
def compute_accuracy(y_true, y_pred):
    pred_classes = np.argmax(y_pred, axis=1)
    true_classes = np.argmax(y_true, axis=1)
    return np.mean(pred_classes == true_classes)

In [ ]:
def get_mini_batches(X, y, batch_size):
    m = X.shape[0]
    indices = np.random.permutation(m)

    for i in range(0, m, batch_size):
        end = min(i + batch_size, m)
        batch_indices = indices[i:end]
        yield X[batch_indices], y[batch_indices]

In [ ]:
def adjust_learning_rate(epoch, initial_lr, decay_rate=0.95, decay_step=10):
    return initial_lr * (decay_rate ** (epoch // decay_step))

In [ ]:
def train_logistic_regression(X_train, y_train, X_val, y_val,
                              initial_lr=0.1, epochs=50, batch_size=64,
                              lambda_reg=0.01, early_stopping_patience=5):

    n_features = X_train.shape[1]
    n_classes = y_train.shape[1]

    # Initialize weights and bias
    W, b = initialize_weights(n_features, n_classes)

    # Track metrics
    train_losses = []
    val_losses = []
    val_accuracies = []

    # For early stopping
    best_val_loss = float('inf')
    patience_counter = 0
    best_W, best_b = None, None

    print("\nStarting training...")
    print(f"Parameters: learning_rate={initial_lr}, batch_size={batch_size}, lambda_reg={lambda_reg}")

    for epoch in range(epochs):
        # Update learning rate with decay
        lr = adjust_learning_rate(epoch, initial_lr)

        # Train on mini-batches
        for X_batch, y_batch in get_mini_batches(X_train, y_train, batch_size):
            # Convert sparse to dense for computation
            X_batch_dense = X_batch.toarray()
            y_batch_dense = y_batch.toarray()

            # Forward pass
            z = X_batch_dense.dot(W) + b
            y_pred = softmax(z)

            # Compute gradients
            dW, db = compute_gradients(X_batch_dense, y_batch_dense, y_pred, W, lambda_reg)

            # Update parameters
            W -= lr * dW
            b -= lr * db

        # Compute metrics at the end of each epoch
        # Training loss
        X_train_sample = X_train[:1000].toarray()
        y_train_sample = y_train[:1000].toarray()
        train_pred = softmax(X_train_sample.dot(W) + b)
        train_loss = compute_loss(y_train_sample, train_pred, W, lambda_reg)
        train_losses.append(train_loss)

        # Validation metrics
        X_val_dense = X_val.toarray()
        y_val_dense = y_val.toarray()
        val_pred = softmax(X_val_dense.dot(W) + b)
        val_loss = compute_loss(y_val_dense, val_pred, W, lambda_reg)
        val_losses.append(val_loss)

        val_accuracy = compute_accuracy(y_val_dense, val_pred)
        val_accuracies.append(val_accuracy)

        # Print progress
        if (epoch + 1) % 5 == 0 or epoch == 0:
            print(f"Epoch {epoch+1}/{epochs}, LR: {lr:.6f}, Train Loss: {train_loss:.4f}, "
                  f"Val Loss: {val_loss:.4f}, Val Accuracy: {val_accuracy:.4f}")

        # Early stopping check
        if val_loss < best_val_loss:
            best_val_loss = val_loss
            best_W, best_b = W.copy(), b.copy()
            patience_counter = 0
        else:
            patience_counter += 1
            if patience_counter >= early_stopping_patience:
                print(f"Early stopping at epoch {epoch+1}")
                break

    # Return the best model if early stopping occurred
    if best_W is not None and best_b is not None:
        W, b = best_W, best_b

    return W, b, train_losses, val_losses, val_accuracies

In [ ]:
W, b, train_losses, val_losses, val_accuracies = train_logistic_regression(
    X_train_sparse, y_train_sparse, X_val_sparse, y_val_sparse,
    initial_lr=0.1, epochs=50, batch_size=64, lambda_reg=0.01
)

Starting training...
Parameters: learning_rate=0.1, batch_size=64, lambda_reg=0.01
Epoch 1/50, LR: 0.100000, Train Loss: 1.5207, Val Loss: 1.5624, Val Accuracy: 0.2916
Epoch 5/50, LR: 0.100000, Train Loss: 1.3898, Val Loss: 1.5406, Val Accuracy: 0.3170
Epoch 10/50, LR: 0.100000, Train Loss: 1.2993, Val Loss: 1.5237, Val Accuracy: 0.3451
Epoch 15/50, LR: 0.095000, Train Loss: 1.2109, Val Loss: 1.5136, Val Accuracy: 0.3515
Epoch 20/50, LR: 0.095000, Train Loss: 1.1390, Val Loss: 1.5063, Val Accuracy: 0.3569
Epoch 25/50, LR: 0.090250, Train Loss: 1.0649, Val Loss: 1.5011, Val Accuracy: 0.3542
Epoch 30/50, LR: 0.090250, Train Loss: 1.0115, Val Loss: 1.4967, Val Accuracy: 0.3560
Epoch 35/50, LR: 0.085737, Train Loss: 0.9576, Val Loss: 1.4936, Val Accuracy: 0.3524
Epoch 40/50, LR: 0.085737, Train Loss: 0.9097, Val Loss: 1.4904, Val Accuracy: 0.3551
Epoch 45/50, LR: 0.081451, Train Loss: 0.8778, Val Loss: 1.4881, Val Accuracy: 0.3624
Epoch 50/50, LR: 0.081451, Train Loss: 0.8421, Val Loss: 1.4862, Val Accuracy: 0.3624

In [ ]:
def evaluate_model(X, y, W, b, dataset_name="Test"):
    X_dense = X.toarray()
    y_dense = y.toarray()

    # Predictions
    predictions = softmax(X_dense.dot(W) + b)

    # Calculate metrics
    # No regularization for evaluation
    loss = compute_loss(y_dense, predictions, W, 0)
    accuracy = compute_accuracy(y_dense, predictions)

    # Get class predictions
    pred_classes = np.argmax(predictions, axis=1)
    true_classes = np.argmax(y_dense, axis=1)

    print(f"\n{dataset_name} Set Evaluation:")
    print(f"Loss: {loss:.4f}")
    print(f"Accuracy: {accuracy:.4f}")


    return loss, accuracy, pred_classes, true_classes

In [ ]:
val_metrics = evaluate_model(X_val_sparse, y_val_sparse, W, b, "Validation")
test_metrics = evaluate_model(X_test_sparse, y_test_sparse, W, b, "Test")

Validation Set Evaluation:
Loss: 1.4843
Accuracy: 0.3624

Test Set Evaluation:
Loss: 1.4956
Accuracy: 0.3511

In [ ]:
sklearn_lr = LogisticRegression(
    multi_class='multinomial',
    #optimization using second order (Hessian matrix), my model uses mini batches for optimization
    solver='lbfgs',
    # C is inverse of regularization strength
    C=1/0.01,
    max_iter=100,
    random_state=42
)
sklearn_lr.fit(X_train_sparse, df_train["class"])
sklearn_lr_preds = sklearn_lr.predict(X_test_sparse)
sklearn_lr_accuracy = accuracy_score(df_test["class"], sklearn_lr_preds)

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(

In [ ]:
sklearn_sgd = SGDClassifier(
    loss='log_loss',
    penalty='l2',
    alpha=0.01,
    max_iter=100,
    random_state=42
)
sklearn_sgd.fit(X_train_sparse, df_train["class"])
sklearn_sgd_preds = sklearn_sgd.predict(X_test_sparse)
sklearn_sgd_accuracy = accuracy_score(df_test["class"], sklearn_sgd_preds)

In [ ]:
print("\nModel Comparison Results:")
print(f"Our Implementation - Test Accuracy: {test_metrics[1]:.4f}")
print(f"Scikit-learn LogisticRegression - Test Accuracy: {sklearn_lr_accuracy:.4f}")
print(f"Scikit-learn SGDClassifier - Test Accuracy: {sklearn_sgd_accuracy:.4f}")

Model Comparison Results:
Our Implementation - Test Accuracy: 0.3511
Scikit-learn LogisticRegression - Test Accuracy: 0.3425
Scikit-learn SGDClassifier - Test Accuracy: 0.3285

Our model's accuracy is higher than scikit-learn logisticRegression maybe because of hyperparameter tunning cause we have tried different values for the learning rate, batch size, number of epochs untill we reached to these values that perform the best   
Our model's accuracy is also higher than scikit-learn SGDClassifier maybe because of scheduling the learning rate and decreasing it's value every 10 epochs
SGDClassifier is more comparable as both use stochastic gradient descent, but
LogisticRegression is more comparable in terms of final performance and it's accuracy is closer to our model's accuracy than SGDClassifier